### ISSUE TITLE
The big TODO list

### ISSUE THREAD

**Issue by HoneyPony** [HoneyPony/poniescript#14]
Here is a list of features that are needed to make PonieScript useful at all. Some of them are simple, some of them are very complicated.

- [x] Comparison operators <, >, etc
- [x] Comments
- [x] Logical operators and/or
- [x] Binary operator %
- [x] Unary ops +, -
- [ ] Unary op !
- [x] Operators +=, -=, *=, /=, %=
- [ ] Comparison operators == and !=
   - Need to decide semantic for string comparisons and such. 
   - [x] == for numerical types
   - [x] != for numerical types
   - [ ] ==, != for strings?
- [x] Assignment of Unbound exprs
- [ ] Loops (for, while)
   - [x] `loop` loop
   - [x] `while` loop
   - [x] `for` loop 
   - [ ] Iterators
   - [x] `range()`
- [x] vec types (`vec2`, `vec3`, etc)
- [x] vec operators (`vec2 + vec2`, `vec3 * float`, etc)
   - [x] element-wise operators
   - [x] vec * scalar products 
- [ ] Fixed point numbers
- [ ] Some builtin math operators
   - [ ] `max`, `min`, `clamp`, 
   - [x] `lerp`
   - [ ] `move_toward`
   - [ ] `dot`, `cross`
- [x] Closures
   - [x] Basic support (e.g. int variables)
   - [x] Basic reference type support
   - [x] Capture of functions, lambas, etc
- [x] Function storability (e.g. `var x = my_fun; x()`)
- [x] Lambdas
- [ ] Extern functions, etc
   - [ ] Extern types? Not sure how this will work exactly. 
- [x] Classes
   - [x] Fields
   - [x] Methods
   - [ ] Inheritance
   - [ ] Subtyping relationships
   - [ ] Getters/setters
   - [ ] Nodes
- [ ] Optional types (e.g. `?Str`, `?MyClass`)
   - [x] Optional pointer types, for the most part
- [ ] Weak node types
- [ ] List types
- [ ] Map types
- [ ] Set types
- [x] Garbage collector
- [ ] Value types
   - [x] Tuples are mostly implemented
- [ ] Enums
   - Not the sum-type type. Probably. Need to figure out what kinds of enums would be good.
   - Easy support for: indexing tables, printing out the string value, comparison with == (something Rust doesn't seem to do nicely) are all desired.
       - Tables in particular might eventually be a built in feature... especially with macros / codegen letting you automatically fill out some entries.
